//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThucTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAY_CNDT
    {
        public string SO_GCNDT { get; set; }
        public int ID_TTHS { get; set; }
        public string MA_CTHTDT { get; set; }
        public string MA_LH { get; set; }
        public string MA_QG { get; set; }
        public string SO_CNDKKD { get; set; }
        public string TEN_DU_AN_TIENG_VIET { get; set; }
        public string TEN_DU_AN_TIENG_ANH { get; set; }
        public string TEN_DU_AN_VIET_TAT { get; set; }
        public System.DateTime NGAY_DANG_KY { get; set; }
        public Nullable<System.DateTime> NGAY_KY { get; set; }
        public string MUC_TIEU_HOAT_DONG { get; set; }
        public string QUI_MO_DU_AN { get; set; }
        public Nullable<decimal> VON_DAU_TU_USD { get; set; }
        public Nullable<decimal> VON_DAU_TU_VND { get; set; }
        public Nullable<decimal> VON_DIEU_LE_USD { get; set; }
        public Nullable<decimal> VON_DIEU_LE_VND { get; set; }
        public Nullable<double> TY_GIA { get; set; }
        public Nullable<double> DIEN_TICH_DAT_SU_DUNG { get; set; }
        public Nullable<double> DIEN_TICH_DAT_THUE { get; set; }
        public Nullable<decimal> TIEN_THUE_DAT_HANG_NAM { get; set; }
        public Nullable<double> DIEN_TICH_DAT_GIAO { get; set; }
        public Nullable<double> DIEN_TICH_NHA_XUONG { get; set; }
        public string SO_CNDKKD_CHO_THUE_NHA_XUONG { get; set; }
        public string CONG_NGHE_XUAT_XU { get; set; }
        public string SAN_PHAM_DV_CHINH { get; set; }
        public string TIEU_CHUAN_KY_THUAT { get; set; }
        public Nullable<double> GTGT_CUA_SAN_PHAM { get; set; }
        public string TRANG_THIET_BI { get; set; }
        public string NANG_LUC_SX { get; set; }
        public string THI_TRUONG_TRONG_NUOC { get; set; }
        public string NGUYEN_VAT_LIEU { get; set; }
        public Nullable<double> PHAN_TRAM_NVL_MUA_TRONG_NUOC { get; set; }
        public string NGUON_CUNG_CAP_NVL { get; set; }
        public string PHAN_TRAM_LKKTC_TU_SX { get; set; }
        public string PHAN_TRAM_LKKTC_DAT_HANG_TRONG_NUOC { get; set; }
        public Nullable<int> THOI_GIAN_HOAT_DONG { get; set; }
        public Nullable<decimal> QUI_MO_NHAP_KHAU { get; set; }
        public Nullable<decimal> QUI_MO_XUAT_KHAU { get; set; }
        public string TIEN_DO_XD { get; set; }
        public string TIEN_DO_MMTB { get; set; }
        public string TIEN_DO_SX_THU { get; set; }
        public string TIEN_DO_SXKD { get; set; }
        public string DUONG_DAN { get; set; }
        public string SO_QD_THU_HOI { get; set; }
        public Nullable<System.DateTime> NGAY_QD_THU_HOI { get; set; }
        public string NGUYEN_NHAN_THU_HOI { get; set; }
    }
}
