//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThucTap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DUAN_KHUCNCEntities : DbContext
    {
        public DUAN_KHUCNCEntities()
            : base("name=DUAN_KHUCNCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TY_LE_CHI_RD> TY_LE_CHI_RD { get; set; }
        public virtual DbSet<TY_LE_LAO_DONG_RD> TY_LE_LAO_DONG_RD { get; set; }
        public virtual DbSet<V_RD> V_RD { get; set; }
    }
}
