//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThucTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TY_LE_LAO_DONG_RD
    {
        public string TEN_DU_AN_TIENG_VIET { get; set; }
        public Nullable<double> NAM_2015 { get; set; }
        public Nullable<double> NAM_2016 { get; set; }
        public Nullable<double> NAM_2017 { get; set; }
        public Nullable<double> NAM_2018 { get; set; }
        public Nullable<double> NAM_2019 { get; set; }
    }
}
