//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThucTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RD
    {
        public string TENDN_VT { get; set; }
        public int NAM { get; set; }
        public Nullable<double> TY_LE_CHI_PHI_RD { get; set; }
        public Nullable<double> TY_LE_DH_TREN_DH_THAM_GIA_RD { get; set; }
        public Nullable<decimal> KINH_PHI { get; set; }
    }
}
